#!/bin/bash
# Cloned from ~straka/bin/run
# Runs a job on the cluster.
# In the original usage, the command would be ~straka/bin.local/withcuda100 (or analogous for other CUDA versions),
# followed by the real job script as the argument. In my clone here, I hardwired withcuda100 below, meaning that
# this version is suitable for training UDPipe 2, but not necessarily for computing word embeddings or inference.
# Also, this version has hardwired the virtual environment with old Python and TensorFlow for training.

[ -n "$SLURM_JOB_ID" ] && echo 🔑 $SLURM_JOB_ID >&2
echo 💻 $(hostname) >&2
[ -n "${SLURM_JOB_GPUS:-$SLURM_STEP_GPUS}$CUDA_VISIBLE_DEVICES" ] && echo 📼 ${SLURM_JOB_GPUS:-$SLURM_STEP_GPUS} $CUDA_VISIBLE_DEVICES >&2
echo 🕑 $(date) >&2
echo 📁 $PWD >&2
echo 📖 "$@" >&2

# DZ: The following lines are taken from ~straka/bin.local/withcuda100

export LD_LIBRARY_PATH="/opt/cuda/10.0/lib64:/opt/cuda/10.0/cudnn/7.6/lib64:/opt/cuda/10.0/extras/CUPTI/lib64:$LD_LIBRARY_PATH"

if [ -z "$CUDA_VISIBLE_DEVICES" ]; then
  echo "CUDA_VISIBLE_DEVICES not set, aborting!" >&2
  exit 1
fi

# DZ: The following is my addition to activate the right venv for Python.

source /net/work/people/zeman/python-env-udpipe-training-lenka/bin/activate

exec /usr/bin/time -f "🚪 %x\n⌛ %E real, %U user, %S sys, %M kB" "$@"
